version: '3'
services:
  redis:
    image: redis
    expose:
    - 6379

  worker:
    image: celery-imdsv2-dev
    command: celery -A tasks worker --loglevel=info
    environment:
    - BROKER_URL=redis://redis:6379/0

  server:
    image: celery-imdsv2-dev
    command: python server.py
    environment:
    - BROKER_URL=redis://redis:6379/0
    ports:
    - 8000:8000
